name: Auto Commit 10 Times

on: 
  workflow_dispatch: # Allows manual triggering of the workflow via the GitHub UI

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Commit changes 10 times
      run: |
        for i in {1..10}
        do
          echo "Auto commit number $i at $(date)" >> README.md
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Auto commit $i"
        done
    
    - name: Push changes
      run: |
        git push
